info:
  app:
    name: Project service - Command Side
    description: Project service - Command Side (CQRS)

management:
  security:
    enabled: false

server:
  port: ${PORT:8082}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    xyz.weechang: DEBUG

mongodb:
  url: 127.0.0.1
  port: 27017
  dbname: taroco
  events:
    collection:
      name: events
    snapshot:
      collection:
        name: snapshots

spring:
  rabbitmq:
    hostname: 127.0.0.1
    username: guest
    password: guest

axon:
  amqp:
    exchange: taroco.evnetBus
      
security:
  oauth2:
    resource:
      jwt:
        keyUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.uri:http://localhost:8761}/eureka/

# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
  hostname: localhost
  port: 9999
  contextPath: uaa