server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  profiles:
    active: "@profileActive@"
  application:
    name: moreco-spring-boot-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  session:
    store-type: redis

logging:
  level: debug
  level.xyz.weechang: debug
  path: logs/

moreco:
  security:
    # 不需要授权的路径
    noAuthPaths: []
    # token过期时间--单位（S）
    tokenExpiredTime: 1800

