server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms

spring:
  profiles:
    active: "@profileActive@"
  application:
    name: moreco-spring-boot-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  session:
    store-type: redis

logging:
  level: debug
  level.io.github.weechang.moreco: debug
  path: logs/
  file: moreco-spring-boot-demo.log

moreco:
  security:
    noAuthPaths: []
  swagger:
    enabled: true
